name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:  
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Tests with Pytest
      run: |
        source venv/bin/activate
        pytest ./tests
